#index:
#    path: /
#    controller: App\Controller\DefaultController::index
create_aluno:
  path: /alunos
  controller: App\Controller\ControllerAluno::createAluno
  methods:
    - POST

update_aluno:
  path: /alunos/{id}
  controller: App\Controller\ControllerAluno::updateAluno
  methods:
    - PUT

list_alunos:
  path: /alunos
  controller: App\Controller\ControllerAluno::search
  methods:
    - GET

create_professor:
  path: /professor
  controller: App\Controller\ControllerProfessor::createProfessor
  methods:
    - POST

list_professor:
  path: /professor
  controller: App\Controller\ControllerProfessor::search
  methods:
    - GET

update_professor:
  path: /professor/{id}
  controller: App\Controller\ControllerProfessor::updateProfessor
  methods:
    - PUT

create_projeto:
  path: /projeto
  controller: App\Controller\ControllerProjeto::create
  methods:
    - POST

update_projeto:
  path: /projeto/{projetoId}
  controller: App\Controller\ControllerProjeto::updateProjeto
  methods:
    - PUT

list_projeto:
  path: /projeto
  controller: App\Controller\ControllerProjeto::search
  methods:
    - GET

vincularAlunoProjeto:
  path: /projeto/vincular/{id}
  controller: App\Controller\ControllerProjeto::vincularAlunoEntity
  methods:
    - PUT

desvincularAlunoProjeto:
  path: /projeto/desvincular/{id_projeto}
  controller: App\Controller\ControllerProjeto::desvincularAluno
  methods:
    - PUT

detail_projeto:
  path: /projeto/{id}
  controller: App\Controller\ControllerProjeto::detalheProjeto
  methods:
    - GET

filter_projeto:
  path: /projetoFiltro/{texto}
  controller: App\Controller\ControllerProjeto::pesquisarProjeto
  methods:
    - GET

removeProjeto:
  path: /projeto/{id}
  controller: App\Controller\ControllerProjeto::remove
  methods:
    - DELETE

create_visitante:
  path: /visitantes
  controller: App\Controller\ControllerVisitante::create
  methods:
    - POST

adicionar_sugestao:
  path: /sugestao
  controller: App\Controller\ControllerSugestao::create
  methods:
    - POST

detalhe_sugestao:
  path: /sugestao
  controller: App\Controller\ControllerSugestao::search
  methods:
    - GET

lista_visitantes:
  path: /visitantes
  controller: App\Controller\ControllerVisitante::search
  methods:
    - GET

remove_visitante:
  path: /visitante/{id}
  controller: App\Controller\ControllerVisitante::remove
  methods:
    - DELETE

create_user:
  path: /visitante
  controller: App\Controller\ControllerVisitante::create