#index:
#    path: /
#    controller: App\Controller\DefaultController::index
create_aluno:
  path: /alunos
  controller: App\Controller\ControllerAluno::createAluno
  methods:
    - POST


alunos:
  path: /alunos
  controller: App\Controller\ControllerAluno::search
  methods:
    - GET

create_professor:
  path: /professor
  controller: App\Controller\ControllerProfessor::createProfessor
  methods:
    - POST

professor:
  path: /professor
  controller: App\Controller\ControllerProfessor::search
  methods:
    - GET

professor_update:
  path: /professor/{id}
  controller: App\Controller\ControllerProfessor::updateProfessor
  methods:
    - PUT

projeto:
  path: /projeto
  controller: App\Controller\ControllerProjeto::search
  methods:
    - GET

create_projeto:
  path: /projeto
  controller: App\Controller\ControllerProjeto::create
  methods:
    - POST

create_visitante:
  path: /visitantes
  controller: App\Controller\ControllerVisitante::create
  methods:
    - POST

vincularAlunoProjeto:
  path: /projeto/vincular/{id}
  controller: App\Controller\ControllerProjeto::vincularAlunoEntity
  methods:
    - PUT

desvincularAlunoProjeto:
  path: /projeto/desvincular/{id_projeto}/{id_aluno}
  controller: App\Controller\ControllerProjeto::desvincularAluno
  methods:
    - PUT

detalheProjeto:
  path: /projeto/{id}
  controller: App\Controller\ControllerProjeto::detalheProjeto
  methods:
    - GET


filtarProjeto:
  path: /projetoFiltro/{texto}
  controller: App\Controller\ControllerProjeto::pesquisarProjeto
  methods:
    - GET

removeProjeto:
  path: /projeto/{id}
  controller: App\Controller\ControllerProjeto::remove
  methods:
    - DELETE

adicionar_sugestao:
  path: /sugestao
  controller: App\Controller\ControllerSugestao::create
  methods:
    - POST

detalhe_sugestao:
  path: /sugestao
  controller: App\Controller\ControllerSugestao::search
  methods:
    - GET

lista_visitantes:
  path: /visitantes
  controller: App\Controller\ControllerVisitante::search
  methods:
    - GET

remove_visitante:
  path: /visitante/{id}
  controller: App\Controller\ControllerVisitante::remove
  methods:
    - DELETE

create_user:
  path: /visitante
  controller: App\Controller\ControllerVisitante::create