#index:
#    path: /
#    controller: App\Controller\DefaultController::index
create_aluno:
  path: /alunos
  controller: App\Controller\ControllerAluno::create
  methods:
    - POST

alunos:
  path: /alunos
  controller: App\Controller\ControllerAluno::search
  methods:
    - GET

create_professor:
  path: /professor
  controller: App\Controller\ControllerProfessor::create
  methods:
    - POST

professor:
  path: /professor
  controller: App\Controller\ControllerProfessor::search
  methods:
    - GET

projeto:
  path: /projeto
  controller: App\Controller\ControllerProjeto::search
  methods:
    - GET

create_projeto:
  path: /projeto
  controller: App\Controller\ControllerProjeto::create
  methods:
    - POST

create_visitante:
  path: /visitantes
  controller: App\Controller\ControllerVisitante::create
  methods:
    - POST

vincular_aluno_entity:
  path: /projeto/vincular/{id}
  controller: App\Controller\ControllerProjeto::vincularAlunoEntity
  methods:
    - PUT

detalheProjeto:
  path: /projeto/{id}
  controller: App\Controller\ControllerProjeto::detalheProjeto
  methods:
    - GET

adicionar_sugestao:
  path: /sugestao
  controller: App\Controller\ControllerSugestao::create
  methods:
    - POST

detalhe_sugestao:
  path: /sugestao
  controller: App\Controller\ControllerSugestao::search
  methods:
    - GET